name: dbt_olist
profile: dbt_olist

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_olist:
    staging:
      +materialized: view
      +schema: silver

    intermediate:
      +materialized: table
      +schema: silver

    marts:
      +materialized: table
      +schema: gold